- name: deploy and start nginx
  hosts: linux
  vars:
    port: 80
    nginx_package: nginx

  tasks:
    - name: install nginx
      yum:
        name: "{{ nginx_package }}"
        state: latest

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: false

    - name: copy nginx conf by jinja2
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/myweb.conf
        owner: root
        group: root
        mode: 0644

    - name: create web content
      copy:
        content: "Hello from {{ ansible_facts['hostname'] }}!"
        dest: /usr/share/nginx/html/index.html
